image: gitpod/workspace-full

tasks:
  - name: Prepare Interview Environment
    init: |
      echo "Interview environment ready!"
      
  - name: Backend Setup
    init: |
      cd backend
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    command: |
      cd backend
      source venv/bin/activate
      echo "Backend environment ready. Python $(python --version)"
      
  - name: Frontend Setup
    init: |
      cd frontend
      npm install
      cd ../challenges
      npm install
    command: |
      cd frontend
      echo "Frontend environment ready. Node $(node --version)"
      
  - name: Challenges
    command: |
      cd challenges
      echo "Welcome to the Ranova Coding Test!"
      echo "=================================="
      echo ""
      echo "Please open the challenges folder to begin."
      echo ""
      echo "1. Python Challenge: python_challenge.py"
      echo "2. React Challenge: react_challenge.tsx"
      echo ""
      echo "Follow the instructions in each file."
      gp open python_challenge.py
      gp open react_challenge.tsx

ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 8000
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss